export const countries = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", currency: "AFN", symbol: "؋" },
  { name: "Albania", code: "AL", flag: "🇦🇱", currency: "ALL", symbol: "L" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", currency: "DZD", symbol: "د.ج" },
  { name: "America (USA)", code: "US", flag: "🇺🇸", currency: "USD", symbol: "$" },
  { name: "Andorra", code: "AD", flag: "🇦🇩", currency: "EUR", symbol: "€" },
  { name: "Angola", code: "AO", flag: "🇦🇴", currency: "AOA", symbol: "Kz" },
  { name: "Argentina", code: "AR", flag: "🇦🇷", currency: "ARS", symbol: "$" },
  { name: "Armenia", code: "AM", flag: "🇦🇲", currency: "AMD", symbol: "֏" },
  { name: "Australia", code: "AU", flag: "🇦🇺", currency: "AUD", symbol: "$" },
  { name: "Austria", code: "AT", flag: "🇦🇹", currency: "EUR", symbol: "€" },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", currency: "AZN", symbol: "₼" },
  { name: "Bahamas", code: "BS", flag: "🇧🇸", currency: "BSD", symbol: "$" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭", currency: "BHD", symbol: ".د.ب" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", currency: "BDT", symbol: "৳" },
  { name: "Barbados", code: "BB", flag: "🇧🇧", currency: "BBD", symbol: "$" },
  { name: "Belarus", code: "BY", flag: "🇧🇾", currency: "BYN", symbol: "Br" },
  { name: "Belgium", code: "BE", flag: "🇧🇪", currency: "EUR", symbol: "€" },
  { name: "Belize", code: "BZ", flag: "🇧🇿", currency: "BZD", symbol: "$" },
  { name: "Benin", code: "BJ", flag: "🇧🇯", currency: "XOF", symbol: "CFA" },
  { name: "Bhutan", code: "BT", flag: "🇧🇹", currency: "BTN", symbol: "Nu." },
  { name: "Bolivia", code: "BO", flag: "🇧🇴", currency: "BOB", symbol: "Bs." },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦", currency: "BAM", symbol: "KM" },
  { name: "Botswana", code: "BW", flag: "🇧🇼", currency: "BWP", symbol: "P" },
  { name: "Brazil", code: "BR", flag: "🇧🇷", currency: "BRL", symbol: "R$" },
  { name: "Brunei", code: "BN", flag: "🇧🇳", currency: "BND", symbol: "$" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬", currency: "BGN", symbol: "лв" },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫", currency: "XOF", symbol: "CFA" },
  { name: "Burundi", code: "BI", flag: "🇧🇮", currency: "BIF", symbol: "FBu" },
  { name: "Cambodia", code: "KH", flag: "🇰🇭", currency: "KHR", symbol: "៛" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲", currency: "XAF", symbol: "FCFA" },
  { name: "Canada", code: "CA", flag: "🇨🇦", currency: "CAD", symbol: "$" },
  { name: "Central African Republic", code: "CF", flag: "🇨🇫", currency: "XAF", symbol: "FCFA" },
  { name: "Chad", code: "TD", flag: "🇹🇩", currency: "XAF", symbol: "FCFA" },
  { name: "Chile", code: "CL", flag: "🇨🇱", currency: "CLP", symbol: "$" },
  { name: "China", code: "CN", flag: "🇨🇳", currency: "CNY", symbol: "¥" },
  { name: "Colombia", code: "CO", flag: "🇨🇴", currency: "COP", symbol: "$" },
  { name: "Congo (DRC)", code: "CD", flag: "🇨🇩", currency: "CDF", symbol: "FC" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷", currency: "CRC", symbol: "₡" },
  { name: "Croatia", code: "HR", flag: "🇭🇷", currency: "EUR", symbol: "€" },
  { name: "Cuba", code: "CU", flag: "🇨🇺", currency: "CUP", symbol: "$" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾", currency: "EUR", symbol: "€" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿", currency: "CZK", symbol: "Kč" },
  { name: "Denmark", code: "DK", flag: "🇩🇰", currency: "DKK", symbol: "kr" },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯", currency: "DJF", symbol: "Fdj" },
  { name: "Dominica", code: "DM", flag: "🇩🇲", currency: "XCD", symbol: "$" },
  { name: "Dominican Republic", code: "DO", flag: "🇩🇴", currency: "DOP", symbol: "RD$" },
  { name: "Ecuador", code: "EC", flag: "🇪🇨", currency: "USD", symbol: "$" },
  { name: "Egypt", code: "EG", flag: "🇪🇬", currency: "EGP", symbol: "£" },
  { name: "El Salvador", code: "SV", flag: "🇸🇻", currency: "USD", symbol: "$" },
  { name: "Estonia", code: "EE", flag: "🇪🇪", currency: "EUR", symbol: "€" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹", currency: "ETB", symbol: "Br" },
  { name: "Fiji", code: "FJ", flag: "🇫🇯", currency: "FJD", symbol: "$" },
  { name: "Finland", code: "FI", flag: "🇫🇮", currency: "EUR", symbol: "€" },
  { name: "France", code: "FR", flag: "🇫🇷", currency: "EUR", symbol: "€" },
  { name: "Gabon", code: "GA", flag: "🇬🇦", currency: "XAF", symbol: "FCFA" },
  { name: "Gambia", code: "GM", flag: "🇬🇲", currency: "GMD", symbol: "D" },
  { name: "Georgia", code: "GE", flag: "🇬🇪", currency: "GEL", symbol: "₾" },
  { name: "Germany", code: "DE", flag: "🇩🇪", currency: "EUR", symbol: "€" },
  { name: "Ghana", code: "GH", flag: "🇬🇭", currency: "GHS", symbol: "₵" },
  { name: "Greece", code: "GR", flag: "🇬🇷", currency: "EUR", symbol: "€" },
  { name: "Grenada", code: "GD", flag: "🇬🇩", currency: "XCD", symbol: "$" },
  { name: "Guatemala", code: "GT", flag: "🇬🇹", currency: "GTQ", symbol: "Q" },
  { name: "Guinea", code: "GN", flag: "🇬🇳", currency: "GNF", symbol: "FG" },
  { name: "Guyana", code: "GY", flag: "🇬🇾", currency: "GYD", symbol: "$" },
  { name: "Haiti", code: "HT", flag: "🇭🇹", currency: "HTG", symbol: "G" },
  { name: "Honduras", code: "HN", flag: "🇭🇳", currency: "HNL", symbol: "L" },
  { name: "Hungary", code: "HU", flag: "🇭🇺", currency: "HUF", symbol: "Ft" },
  { name: "Iceland", code: "IS", flag: "🇮🇸", currency: "ISK", symbol: "kr" },
  { name: "India", code: "IN", flag: "🇮🇳", currency: "INR", symbol: "₹" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩", currency: "IDR", symbol: "Rp" },
  { name: "Iran", code: "IR", flag: "🇮🇷", currency: "IRR", symbol: "﷼" },
  { name: "Iraq", code: "IQ", flag: "🇮🇶", currency: "IQD", symbol: "ع.د" },
  { name: "Ireland", code: "IE", flag: "🇮🇪", currency: "EUR", symbol: "€" },
  { name: "Israel", code: "IL", flag: "🇮🇱", currency: "ILS", symbol: "₪" },
  { name: "Italy", code: "IT", flag: "🇮🇹", currency: "EUR", symbol: "€" },
  { name: "Jamaica", code: "JM", flag: "🇯🇲", currency: "JMD", symbol: "J$" },
  { name: "Japan", code: "JP", flag: "🇯🇵", currency: "JPY", symbol: "¥" },
  { name: "Jordan", code: "JO", flag: "🇯🇴", currency: "JOD", symbol: "د.ا" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿", currency: "KZT", symbol: "₸" },
  { name: "Kenya", code: "KE", flag: "🇰🇪", currency: "KES", symbol: "KSh" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼", currency: "KWD", symbol: "د.ك" },
  { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬", currency: "KGS", symbol: "с" },
  { name: "Laos", code: "LA", flag: "🇱🇦", currency: "LAK", symbol: "₭" },
  { name: "Latvia", code: "LV", flag: "🇱🇻", currency: "EUR", symbol: "€" },
  { name: "Lebanon", code: "LB", flag: "🇱🇧", currency: "LBP", symbol: "ل.ل" },
  { name: "Lesotho", code: "LS", flag: "🇱🇸", currency: "LSL", symbol: "L" },
  { name: "Liberia", code: "LR", flag: "🇱🇷", currency: "LRD", symbol: "$" },
  { name: "Libya", code: "LY", flag: "🇱🇾", currency: "LYD", symbol: "ل.د" },
  { name: "Liechtenstein", code: "LI", flag: "🇱🇮", currency: "CHF", symbol: "Fr" },
  { name: "Lithuania", code: "LT", flag: "🇱🇹", currency: "EUR", symbol: "€" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺", currency: "EUR", symbol: "€" },
  { name: "Madagascar", code: "MG", flag: "🇲🇬", currency: "MGA", symbol: "Ar" },
  { name: "Malawi", code: "MW", flag: "🇲🇼", currency: "MWK", symbol: "MK" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", currency: "MYR", symbol: "RM" },
  { name: "Maldives", code: "MV", flag: "🇲🇻", currency: "MVR", symbol: "Rf" },
  { name: "Mali", code: "ML", flag: "🇲🇱", currency: "XOF", symbol: "CFA" },
  { name: "Malta", code: "MT", flag: "🇲🇹", currency: "EUR", symbol: "€" },
  { name: "Mauritania", code: "MR", flag: "🇲🇷", currency: "MRU", symbol: "UM" },
  { name: "Mauritius", code: "MU", flag: "🇲🇺", currency: "MUR", symbol: "₨" },
  { name: "Mexico", code: "MX", flag: "🇲🇽", currency: "MXN", symbol: "$" },
  { name: "Moldova", code: "MD", flag: "🇲🇩", currency: "MDL", symbol: "L" },
  { name: "Monaco", code: "MC", flag: "🇲🇨", currency: "EUR", symbol: "€" },
  { name: "Mongolia", code: "MN", flag: "🇲🇳", currency: "MNT", symbol: "₮" },
  { name: "Montenegro", code: "ME", flag: "🇲🇪", currency: "EUR", symbol: "€" },
  { name: "Morocco", code: "MA", flag: "🇲🇦", currency: "MAD", symbol: "د.م." },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿", currency: "MZN", symbol: "MT" },
  { name: "Myanmar", code: "MM", flag: "🇲🇲", currency: "MMK", symbol: "K" },
  { name: "Namibia", code: "NA", flag: "🇳🇦", currency: "NAD", symbol: "$" },
  { name: "Nepal", code: "NP", flag: "🇳🇵", currency: "NPR", symbol: "₨" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱", currency: "EUR", symbol: "€" },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿", currency: "NZD", symbol: "$" },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮", currency: "NIO", symbol: "C$" },
  { name: "Niger", code: "NE", flag: "🇳🇪", currency: "XOF", symbol: "CFA" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", currency: "NGN", symbol: "₦" },
  { name: "North Korea", code: "KP", flag: "🇰🇵", currency: "KPW", symbol: "₩" },
  { name: "North Macedonia", code: "MK", flag: "🇲🇰", currency: "MKD", symbol: "ден" },
  { name: "Norway", code: "NO", flag: "🇳🇴", currency: "NOK", symbol: "kr" },
  { name: "Oman", code: "OM", flag: "🇴🇲", currency: "OMR", symbol: "ر.ع." },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", currency: "PKR", symbol: "₨" },
  { name: "Panama", code: "PA", flag: "🇵🇦", currency: "PAB", symbol: "B/." },
  { name: "Papua New Guinea", code: "PG", flag: "🇵🇬", currency: "PGK", symbol: "K" },
  { name: "Paraguay", code: "PY", flag: "🇵🇾", currency: "PYG", symbol: "₲" },
  { name: "Peru", code: "PE", flag: "🇵🇪", currency: "PEN", symbol: "S/." },
  { name: "Philippines", code: "PH", flag: "🇵🇭", currency: "PHP", symbol: "₱" },
  { name: "Poland", code: "PL", flag: "🇵🇱", currency: "PLN", symbol: "zł" },
  { name: "Portugal", code: "PT", flag: "🇵🇹", currency: "EUR", symbol: "€" },
  { name: "Qatar", code: "QA", flag: "🇶🇦", currency: "QAR", symbol: "ر.ق" },
  { name: "Romania", code: "RO", flag: "🇷🇴", currency: "RON", symbol: "lei" },
  { name: "Russia", code: "RU", flag: "🇷🇺", currency: "RUB", symbol: "₽" },
  { name: "Rwanda", code: "RW", flag: "🇷🇼", currency: "RWF", symbol: "FRw" },
  { name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳", currency: "XCD", symbol: "$" },
  { name: "Saint Lucia", code: "LC", flag: "🇱🇨", currency: "XCD", symbol: "$" },
  { name: "Samoa", code: "WS", flag: "🇼🇸", currency: "WST", symbol: "T" },
  { name: "San Marino", code: "SM", flag: "🇸🇲", currency: "EUR", symbol: "€" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", currency: "SAR", symbol: "ر.س" },
  { name: "Senegal", code: "SN", flag: "🇸🇳", currency: "XOF", symbol: "CFA" },
  { name: "Serbia", code: "RS", flag: "🇷🇸", currency: "RSD", symbol: "дин." },
  { name: "Seychelles", code: "SC", flag: "🇸🇨", currency: "SCR", symbol: "₨" },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱", currency: "SLL", symbol: "Le" },
  { name: "Singapore", code: "SG", flag: "🇸🇬", currency: "SGD", symbol: "$" },
  { name: "Slovakia", code: "SK", flag: "🇸🇰", currency: "EUR", symbol: "€" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮", currency: "EUR", symbol: "€" },
  { name: "Somalia", code: "SO", flag: "🇸🇴", currency: "SOS", symbol: "S" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦", currency: "ZAR", symbol: "R" },
  { name: "South Korea", code: "KR", flag: "🇰🇷", currency: "KRW", symbol: "₩" },
  { name: "South Sudan", code: "SS", flag: "🇸🇸", currency: "SSP", symbol: "£" },
  { name: "Spain", code: "ES", flag: "🇪🇸", currency: "EUR", symbol: "€" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰", currency: "LKR", symbol: "₨" },
  { name: "Sudan", code: "SD", flag: "🇸🇩", currency: "SDG", symbol: "ج.س." },
  { name: "Suriname", code: "SR", flag: "🇸🇷", currency: "SRD", symbol: "$" },
  { name: "Sweden", code: "SE", flag: "🇸🇪", currency: "SEK", symbol: "kr" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭", currency: "CHF", symbol: "Fr" },
  { name: "Syria", code: "SY", flag: "🇸🇾", currency: "SYP", symbol: "£" },
  { name: "Taiwan", code: "TW", flag: "🇹🇼", currency: "TWD", symbol: "NT$" },
  { name: "Tajikistan", code: "TJ", flag: "🇹🇯", currency: "TJS", symbol: "SM" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿", currency: "TZS", symbol: "TSh" },
  { name: "Thailand", code: "TH", flag: "🇹🇭", currency: "THB", symbol: "฿" },
  { name: "Timor-Leste", code: "TL", flag: "🇹🇱", currency: "USD", symbol: "$" },
  { name: "Togo", code: "TG", flag: "🇹🇬", currency: "XOF", symbol: "CFA" },
  { name: "Tonga", code: "TO", flag: "🇹🇴", currency: "TOP", symbol: "T$" },
  { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹", currency: "TTD", symbol: "TT$" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳", currency: "TND", symbol: "د.ت" },
  { name: "Turkey", code: "TR", flag: "🇹🇷", currency: "TRY", symbol: "₺" },
  { name: "Turkmenistan", code: "TM", flag: "🇹🇲", currency: "TMT", symbol: "T" },
  { name: "Uganda", code: "UG", flag: "🇺🇬", currency: "UGX", symbol: "USh" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦", currency: "UAH", symbol: "₴" },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪", currency: "AED", symbol: "د.إ" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧", currency: "GBP", symbol: "£" },
  { name: "United States", code: "US", flag: "🇺🇸", currency: "USD", symbol: "$" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾", currency: "UYU", symbol: "$U" },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿", currency: "UZS", symbol: "лв" },
  { name: "Vanuatu", code: "VU", flag: "🇻🇺", currency: "VUV", symbol: "VT" },
  { name: "Vatican City", code: "VA", flag: "🇻🇦", currency: "EUR", symbol: "€" },
  { name: "Venezuela", code: "VE", flag: "🇻🇪", currency: "VES", symbol: "Bs.S" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", currency: "VND", symbol: "₫" },
  { name: "Yemen", code: "YE", flag: "🇾🇪", currency: "YER", symbol: "﷼" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲", currency: "ZMW", symbol: "ZK" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼", currency: "ZWL", symbol: "$" }
];
